### ISSUE TITLE
(pet-use-poetry-p) doesn't find poetry

### ISSUE THREAD

**Issue by janoc** [wyuenho/emacs-pet#4]
Hello, 

I can't manage to get `(pet-use-poetry-p)` to ever detect `poetry`. 

The problem seems to be in this block that always returns nil:

```lisp
  (and (not
        (null
         (string-match-p
          "poetry"
          (or (let-alist (pet-pyproject)
                .build-system.build-backend)
              ""))))
       (executable-find "poetry"))
```
The `string-match-p` always returns nil, so the `and` shortcircuits and the executable is never found, despite `poetry` being in the path. If I remove everything apart from the `executable-find`, then everything works as expected. 

How to reproduce:
   - Create Poetry project with the default config, make sure the `virtualenvs.in-project` settings has default value `null` and thus virtualenvs are **not** created inside of the project directory (otherwise the code finds the `.venv` directory instead of going through the `poetry` detection). 
   - Open the python file in `emacs` and enable `pet-mode`. 
   - `(pet-use-poetry-p)` will evaluate to `nil`
   - `pet-virtualenv-root` is `nil`

**Comment by janoc** [comment]
Pretty much the default as generated by `poetry new` except for the `graphics.py` dependency. But the same thing happens also on my work projects with much bigger `pyproject.toml`

```toml
[tool.poetry]
name = "Bezier"
version = "0.1.0"
description = ""
authors = ["Jan Ciger <jan.ciger@xxx.xxx>"]

[tool.poetry.dependencies]
python = "^3.8"
"graphics.py" = "^5.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
